Veterinaria/Veterinaria/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

from myapps.general.views import Configuraciones

#URL's globales
#Aca van a ir las url de cada aplicacion
#Iran organizadas en orden.


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^carnet/', include('myapps.carnet.urls',namespace='carnet')),
    url(r'^clientes/', include('myapps.clientes.urls',namespace='clientes')),
    url(r'^inventario/', include('myapps.inventario.urls',namespace='inventario')),
    url(r'^planilla/', include('myapps.planilla.urls',namespace='planilla')),
    url(r'^servicios/', include('myapps.servicios.urls',namespace='servicios')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
    url(r'^usuario/', include('myapps.usuario.urls',namespace='usuario')),
     url(r'^logout/', logout_then_login, name='logout'),
     url(r'^$', login, {'template_name':'login.html'}, name='login'),
     url(r'^reset/password_reset', password_reset,
        {'template_name':'registration/forgot-password.html',
        'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),


    url(r'^ventas/', include('myapps.ventas.urls',namespace='ventas')),
    url(r'^index/', include('myapps.general.urls',namespace='general')),

]

Veterinaria/myapps/carnet/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from myapps.carnet.views import index, CarnetCreate, CarnetList, servicio_futuro, listar_proximasCitas,\
carnet_detalle, carnet_list

#URL's de la aplicacion
#Se listan todas las urls de la aplicacion
urlpatterns = [
    url(r'^$', index),
    url(r'^nuevo', login_required(CarnetCreate.as_view()), name='carnet_crear'),
    url(r'^listar', login_required(CarnetList.as_view()), name='carnet_listar'),
    url(r'^carnets_mascotas/(?P<pk>\d+)$', login_required(carnet_list), name='mascota_carnets'),
    url(r'^detalle_todo/(?P<pk>\d+)$', login_required(carnet_detalle), name='carnet_detalle_todo'),
    url(r'^programar_cita', login_required(servicio_futuro), name='carnet_proximaCita'),
    url(r'^citas_programadas/(?P<pk>\d+)$', login_required(listar_proximasCitas), name='carnet_citasProgramadas'),
]

Veterinaria/myapps/clientes/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from myapps.clientes.views import index
from myapps.clientes.views import index, cliente_create ,ClientesList, ClienteCreate
from myapps.clientes.views import pet_create,PetList,PetCreate, pet_list, PetEdit, ClienteEdit,matar_mascota
#URL's de la aplicacion
#Se listan todas las urls de la aplicacion
urlpatterns = [
    url(r'^$', index),
    url(r'^listar', login_required(ClientesList.as_view()), name='clientes_listar'),
    url(r'^nuevo', login_required(ClienteCreate.as_view()), name='cliente_crear'),
    url(r'^editar/(?P<pk>\d+)$',login_required(ClienteEdit.as_view()), name='cliente_editar'),
    url(r'^nuevamascota', login_required(pet_create), name='mascota_crear'),
    url(r'^mascota_editar/(?P<pk>\d+)$',login_required(PetEdit.as_view()), name='mascota_editar'),
    url(r'^mascotas_listar/(?P<pk>\d+)$', login_required(pet_list),name='mascota_listar'),
    url(r'^anular_mascota/(?P<pk>\d+)$', login_required(matar_mascota),name='matar_mascota'),
]

Veterinaria/myapps/clientes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

#Modelo para la tabla Clientes
class Clientes(models.Model):
	codigo = models.CharField(max_length = 45)
	nombres = models.CharField(max_length = 45)
	apellidos = models.CharField(max_length = 45)
	direccion = models.CharField(max_length = 45)
	telefono = models.CharField(max_length = 45)
	email = models.EmailField()
	numero_Mascotas = models.IntegerField(default = 0)

	def __unicode__(self):
		return '{} {}'.format(self.nombres, self.apellidos) #retornar el atributo

#Modelo para la tabla Mascota
class Mascota(models.Model):
	g = (('M','Macho'),('H','Hembra'))
	t = (('Canino','Canino'),('Felino','Felino'),('Ave','Ave'),('Reptil','Reptil'),('Roedor','Roedor'))
	codigo = models.CharField(max_length = 45)
	nombre = models.CharField(max_length = 45)
	raza = models.CharField(max_length = 45)
	edad = models.IntegerField()
	genero = models.CharField(max_length = 45,choices=g)
	tipo_mascota = models.CharField(max_length = 45,choices=t)
	estado = models.BooleanField()
	cliente = models.ForeignKey(Clientes, null=True, blank=True)

	def __unicode__(self):
		return '{} {}{}{}'.format(self.nombre, "(",self.codigo,")") #retornar el atributo

Veterinaria/myapps/clientes/forms.py
from django import forms
from myapps.clientes.models import Clientes
from myapps.clientes.models import Mascota

#Formulario de cliente
#Formulario para ingresar nuevo cliente o mostrar datos del cliente
class ClientesForm(forms.ModelForm):
	class Meta:
		model = Clientes
		#campos
		fields = [
			'codigo',
			'nombres',
			'apellidos',
			'direccion',
			'telefono',
			'email',
		]

		#Labels
		labels = {
			'codigo' : 'Codigo',
			'nombres' : 'Nombres',
			'apellidos' : 'Apellidos',
			'direccion' : 'Direccion',
			'telefono' : 'Telefono',
			'email' : 'Correo electronico',
		}

		#Tipos de campos
		widgets = {
			'codigo' : forms.TextInput(attrs={'class':'form-control'}),
			'nombres' : forms.TextInput(attrs={'class':'form-control'}),
			'apellidos' : forms.TextInput(attrs={'class':'form-control'}),
			'direccion' : forms.TextInput(attrs={'class':'form-control'}),
			'telefono' : forms.NumberInput(attrs={'class':'form-control'}),
			'email' : forms.EmailInput(attrs={'class':'form-control'}),
		}


#Formulario de mascota. Se relaciona directamente con cliente.
#Formulario para ingresar nuevo cliente o mostrar datos del cliente
class MascotaForm(forms.ModelForm):
	class Meta:
		model = Mascota
		#campos
		fields = [
			'cliente',
			'codigo',
			'nombre',
			'tipo_mascota',
			'raza',
			'genero',
			'edad',
			'estado',
		]

		#Labels
		labels = {
			'cliente' : 'Cliente',
			'codigo' : 'Codigo',
			'nombre' : 'Nombre',
			'tipo_mascota' : 'Tipo',
			'raza' : 'Raza',
			'genero' : 'Genero',
			'edad' : 'Edad',
			'estado' : 'Estado',
		}

		#Tipos de campos
		widgets = {
			'cliente' : forms.Select(attrs={'class':'form-control'}),
			'codigo' : forms.TextInput(attrs={'class':'form-control'}),
			'nombre' : forms.TextInput(attrs={'class':'form-control'}),
			'tipo_mascota' : forms.Select(attrs={'class':'form-control'}),
			'raza' : forms.TextInput(attrs={'class':'form-control'}),
			'genero' : forms.Select(attrs={'class':'form-control'}),
			'edad' : forms.NumberInput(attrs={'class':'form-control'}),
			'estado' : forms.HiddenInput(),
		}

Veterinaria/myapps/clientes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy

from myapps.clientes.models import Clientes, Mascota
from myapps.carnet.models import Carnet
from myapps.clientes.forms import ClientesForm, MascotaForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
# Create your views here.

#Vista de prueba
def index(request):
	return render(request,'clientes/index.html')

def cliente_list(request):
	clientes = clientes.objects.all().order_by('id')#para odenar por id :)
	contexto = {'clientes':clientes}
	return render(request,'clientes/clientes_list.html',contexto)

def cliente_create(request):
	if request.method == 'POST':
		form = ClientesForm(request.POST)
		if form.is_valid():
			item = form.save(commit=False)
			item.numero_Mascotas = 0
			item.save()
		return redirect('clientes:clientes_listar')
	else:
		form = ClientesForm()

	return render(request, 'clientes/clientes_form.html',{'form':form})

def matar_mascota(request,pk):
	mascota = Mascota.objects.get(pk=pk)
	mascota.estado = False
	mascota.save()
	return redirect('clientes:clientes_listar')


class ClienteCreate(CreateView):
	model = Clientes
	form_class = ClientesForm
	template_name = 'clientes/clientes_form.html'
	success_url = reverse_lazy('clientes:clientes_listar')

#listar clientes
class ClientesList(ListView):
	model = Clientes
	template_name = 'clientes/clientes_list.html'

#Mascotas
def pet_list(request,pk):
	mascotas = Mascota.objects.filter(cliente=pk).order_by('id')#para odenar por id :)
	c = mascotas.iterator().next()
	contexto = {'Mascotas':mascotas,'Cliente':c.cliente}
	return render(request,'clientes/mostrar_mascotas.html',contexto)

def pet_create(request):
	if request.method == 'POST':
		form = MascotaForm(request.POST)
		if form.is_valid():
			#form.estado = 1
			item = form.save(commit=False)
			item.estado = True
			item.save()
			cliente = Clientes.objects.filter(pk=item.cliente.id)
			c = cliente.iterator().next() 
			c.numero_Mascotas = c.numero_Mascotas + 1
			c.save()
		return redirect('clientes:clientes_listar')
	else:
		form = MascotaForm()

	return render(request, 'clientes/mascota_form.html',{'form':form})

#Vista para crear clientes


	#Vista para crear mascotas
class PetCreate(CreateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'clientes/mascota_form.html'
	success_url = reverse_lazy('clientes:mascota_listar')

#listar clientes
class PetList(ListView):
	model = Mascota
	template_name = 'clientes/mostrar_mascotas.html'

class PetEdit(UpdateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'clientes/mascota_form.html'
	success_url = reverse_lazy('clientes:clientes_listar')

class ClienteEdit(UpdateView):
	model = Clientes
	form_class = ClientesForm
	template_name = 'clientes/clientes_form.html'
	success_url = reverse_lazy('clientes:clientes_listar')

Veterinaria/templates/clientes/clientes_form.html
{% extends 'base/base.html'%}

{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="{% url 'clientes:clientes_listar' %}">Clientes</a>
    </li>
        <li class="breadcrumb-item active">Crear</li>
</ol>
<div class="card mb-3">
	<div class="card-header">
		<i class="fa fa-plus-square"></i>  Datos del Cliente</div>
		<div class="card-body">
			<!-- Adentro de este div va lo que se quiera mostar-->
		<form method="post">
			<!--token de seguridad, IMPORTANTE INCLUIRLO EN TODOS LOS FORMULARIOS-->
			{% csrf_token %} 
			{{form.as_p}}
			<button class="btn btn-primary" type="submit">
				<i class="fa fa-check-square"></i> Guardar</button>
		</form>
		</div>
	</div>
</div>
{% endblock %}

Veterinaria/templates/clientes/clientes_list.html
{% extends 'base/base.html'%}
{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="#">Clientes</a>
    </li>
        <li class="breadcrumb-item active">Listado</li>
</ol>
<div class="card mb-3">
	<div class="card-header"><i class="fa fa-table"></i> Clientes Existentes</div>
	<div class="card-body">
		<div class="table-responsive">
			<table id="tabla1" class="table table-bordered">
				<thead>
					<tr>
						<th>Codigo</th>
						<th>Nombre</th>
						<th>Apellidos</th>
						<th>Dirección</th>
						<th>Telefono</th>
						<th>Email</th>
						<th>Cantidad de mascotas</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
					{% if object_list %}
					{% for clientes in object_list %}
					<tr>
						<td>{{ clientes.codigo}}</td>
						<td>{{ clientes.nombres }}</td>
						<td>{{ clientes.apellidos }}</td>
						<td>{{ clientes.direccion }}</td>
						<td>{{ clientes.telefono }}</td>
						<td>{{ clientes.email }}</td>
						<td>{{ clientes.numero_Mascotas }}</td>
						<td class="text-center">
							<a class="btn btn-primary" href="{% url 'clientes:mascota_listar' clientes.id %}"><i class="fa fa-paw"></i>   Ver Mascotas</a>
							<a class="btn btn-primary" href="{% url 'clientes:cliente_editar' clientes.id %}"><i class="fa fa-pencil-square-o"></i>  Editar</a>
						</td>
					</tr>
					{% endfor %}
					{% else %}
					<h3>No hay registros </h3>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

Veterinaria/templates/clientes/mascota_form.html
{% extends 'base/base.html'%}

{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="{% url 'clientes:clientes_listar' %}">Mascotas</a>
    </li>
        <li class="breadcrumb-item active">Crear</li>
</ol>
<div class="card mb-3">
	<div class="card-header">
		<i class="fa fa-plus-square"></i>  Datos de la Mascota</div>
		<div class="card-body">
			<!-- Adentro de este div va lo que se quiera mostar-->
		<form method="post">
			<!--token de seguridad, IMPORTANTE INCLUIRLO EN TODOS LOS FORMULARIOS-->
			{% csrf_token %} 
			{{form.as_p}}
			<button class="btn btn-primary" type="submit">
				<i class="fa fa-check-square"></i> Guardar</button>
		</form>
		</div>
	</div>
</div>
{% endblock %}

Veterinaria/templates/clientes/mostrar_mascotas.html
{% extends 'base/base.html'%}

{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="{% url 'clientes:clientes_listar' %}">Clientes</a>
    </li>
        <li class="breadcrumb-item active">Listado de Mascotas</li>
</ol>
<div class="card mb-3">
	<div class="card-header"><i class="fa fa-table"></i> Mascotas Existentes de {{Cliente}}</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Codigo</th>
						<th>Nombre</th>
						<th>Raza</th>
						<th>Edad</th>
						<th>Genero</th>
						<th>Tipo de mascota</th>
						<th>Estado</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
					{% if Mascotas %}
					{% for mascota in Mascotas %}
					<tr>
						<td>{{ mascota.codigo }}</td>
						<td>{{ mascota.nombre }}</td>
						<td>{{ mascota.raza }}</td>
						<td>{{ mascota.edad }}</td>
						<td>{{ mascota.genero }}</td>
						<td>{{ mascota.tipo_mascota }}</td>
						{% if mascota.estado %}
							<td>Activo</td>
						{% else %}
							<td>Inactivo</td>
						{% endif %}
						<td class="text-center">
							<a class="btn btn-primary" href="{% url 'clientes:mascota_editar' mascota.id %}"><i class="fa fa-pencil-square-o"></i>  Editar</a>
							<a class="btn btn-primary" href="{% url 'carnet:mascota_carnets' mascota.id %}"><i class="fa fa-address-card"></i>   Ver Carnets</a>
							<a class="btn btn-primary" href="{% url 'clientes:matar_mascota' mascota.id %}"><i class="fa fa-ban"></i>  Anular Mascota</a>
						</td>
					</tr>
					{% endfor %}
					{% else %}
					<h3>No hay mascotas registradas</h3>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}