Veterinaria/Veterinaria/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

from myapps.general.views import Configuraciones

#URL's globales
#Aca van a ir las url de cada aplicacion
#Iran organizadas en orden.


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^carnet/', include('myapps.carnet.urls',namespace='carnet')),
    url(r'^clientes/', include('myapps.clientes.urls',namespace='clientes')),
    url(r'^inventario/', include('myapps.inventario.urls',namespace='inventario')),
    url(r'^planilla/', include('myapps.planilla.urls',namespace='planilla')),
    url(r'^servicios/', include('myapps.servicios.urls',namespace='servicios')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
    url(r'^usuario/', include('myapps.usuario.urls',namespace='usuario')),
     url(r'^logout/', logout_then_login, name='logout'),
     url(r'^$', login, {'template_name':'login.html'}, name='login'),
     url(r'^reset/password_reset', password_reset,
        {'template_name':'registration/forgot-password.html',
        'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),


    url(r'^ventas/', include('myapps.ventas.urls',namespace='ventas')),
    url(r'^index/', include('myapps.general.urls',namespace='general')),

]

Veterinaria/myapps/general/urls.py
from django.conf.urls import url

from myapps.general.views import calcular_total
from django.contrib.auth.decorators import login_required

from myapps.general.views import ConfiUpdate
#URL's de la aplicacion
#Se listan todas las urls de la aplicacion
urlpatterns = [
    url(r'^$',  login_required(calcular_total), name='resumen_datos'),
    url(r'^parametrizacion/(?P<pk>\d+)$',  login_required(ConfiUpdate.as_view()), name='configuracion'),

]

Veterinaria/myapps/servicios/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from myapps.servicios.views import index, servicios_list, servicios_create, ServiciosList, \
 									detalle_servicios,ServiciosUpdate,obtener_precio_ajax,\
 									existencia_servicio

#URL's de la aplicacion
#Se listan todas las urls de la aplicacion
urlpatterns = [
    url(r'^$', index),
    url(r'^listar', login_required(servicios_list), name='servicios_listar'),
    url(r'^nuevo', login_required(servicios_create), name='servicios_crear'),
    url(r'^detalle/(?P<pk>\d+)$', login_required(detalle_servicios), name='servicios_detalle'),
    url(r'^editar/(?P<pk>\d+)$', login_required(ServiciosUpdate.as_view()), name='servicios_editar'),
    url(r'^ajax/get_precio/$', obtener_precio_ajax, name='get_precio'),
    url(r'^ajax/get_existencia/$', existencia_servicio, name='get_existencia'),
]

Veterinaria/myapps/ventas/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from myapps.ventas.views import index, venta_create, ventas_list, detalle_ventas,venta_programada


urlpatterns = [
	url(r'^$', index),
	url(r'^nuevo', login_required(venta_create), name='ventas_crear'),
	url(r'^listar', login_required(ventas_list), name='ventas_listar'),
	url(r'^detalle/(?P<pk>\d+)$', login_required(detalle_ventas), name='ventas_detalle'),
	url(r'^programada/(?P<pk>\d+)$', login_required(venta_programada), name='ventas_programadas'),
]

Veterinaria/myapps/ventas/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from myapps.carnet.models import Carnet
from myapps.servicios.models import Servicios
# Create your models here.

#Modelo para la tabla ventas
class Ventas(models.Model):
	fecha = models.DateField()
	cantidad = models.IntegerField(default = 0)
	total = models.DecimalField(max_digits = 7,decimal_places=2,default=0)
	carnet = models.ForeignKey(Carnet,null=True,blank=True)

class DetalleVentas(models.Model):
	venta = models.ForeignKey(Ventas,null=True,blank=True)
	servicio = models.ForeignKey(Servicios,null=True,blank=True)

Veterinaria/myapps/ventas/forms.py
from django import forms
from myapps.ventas.models import Ventas,DetalleVentas
from django.utils import timezone
import datetime

#Formulario para realizar una venta
class VentasForm(forms.ModelForm):
	class Meta:
		model = Ventas

		fields = [
			'fecha',
			'carnet',
		]

		labels = {
			'fecha' : 'Fecha',
			'carnet' : 'Carnet Mascota',
		}

		widgets = {
			'fecha' : forms.SelectDateWidget(),
			'carnet' : forms.Select(attrs={'class':'form-control'}),
		}

class DetalleVentasForm(forms.ModelForm):
	class Meta:
		model = DetalleVentas
		fields = ['servicio']

		labels = {'servicio' : 'Servicio'}

		widgets = {
			'servicio' : forms.Select(attrs={'class':'form-control'}),
		}

Veterinaria/myapps/ventas/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.utils import timezone
from datetime import datetime
#Vistas genericas
from django.forms.formsets import formset_factory, BaseFormSet
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
#Forms
from myapps.ventas.forms import VentasForm, DetalleVentasForm
from myapps.ventas.models import Ventas, DetalleVentas
from myapps.carnet.models import DetalleCarnet, Carnet
#Vista de carnet 
from myapps.carnet.views import servicio_nuevo_echo
from myapps.servicios.views import verificar_Existencias, descargarInsumoServicio

from myapps.general.views import Configuraciones
from decimal import Decimal
# Create your views here.

#Vista de prueba
def index(request):
	return HttpResponse('App de Ventas')

#Vista para insertar a la BD
def venta_create(request):
	TodoItemFormSet = formset_factory(DetalleVentasForm, max_num=100, formset=BaseFormSet, extra=1)
	if request.method == 'POST':
		form = VentasForm(request.POST)
		form2 = TodoItemFormSet(request.POST,request.FILES)
		if form.is_valid() and form2.is_valid():
			nueva_venta = form.save(commit=False)
			cantif = 0
			preciof = 0 
			nueva_venta.save()
			n = form.save()
			for f in form2.forms:
				item = f.save(commit=False)
				item.venta = n
				item.save()
				cantif = cantif + 1
				preciof = preciof + item.servicio.precio
				#Se crea el detalle carnet
				servicio_nuevo_echo(n,item)
				#Se descarga de inventario
				descargarInsumoServicio(item.servicio.id)

			nueva_venta.cantidad = cantif
			nueva_venta.total = preciof
			nueva_venta.save()
		return redirect('ventas:ventas_listar')
	else:
		form = VentasForm()
		form2 = TodoItemFormSet()
	nom = Configuraciones.objects.get(pk=1)
	c = {'form': form,'form2': form2,'nombreE':nom.nombre}

	tipo = Configuraciones.objects.get(pk=1)
	tipo = tipo.tipo_cambio
	if tipo == "Q":
		return render(request, 'ventas/ventas_form.html',c)
	if tipo == "D":
		return render(request, 'ventas/ventas_formD.html',c)
	if tipo == "E":
		return render(request, 'ventas/ventas_formE.html',c)
	else:
		return render(request, 'ventas/ventas_form.html',c)

#Vista para realizar un servicio segun uno programado anteriormente

#Vista para listar todas las ventas
def ventas_list(request):
	ventas = Ventas.objects.all().order_by('-fecha')
	tipo = Configuraciones.objects.get(pk=1)
	tipo = tipo.tipo_cambio
	nom = Configuraciones.objects.get(pk=1)
	if(tipo == "D"):
		ventas = convertiraDolares(ventas)
		contexto = {'ventas':ventas,'nombreE':nom.nombre}
		return render(request,'ventas/ventas_listD.html',contexto)
	if(tipo == "E"):
		ventas = convertirEuros(ventas)
		contexto = {'ventas':ventas,'nombreE':nom.nombre}
		return render(request,'ventas/ventas_listE.html',contexto)
	contexto = {'ventas':ventas,'nombreE':nom.nombre}
	return render(request,'ventas/ventas_list.html',contexto)

def convertiraDolares(ventas):
	for v in ventas:
		v.total = round((v.total / Decimal(7.72)),2)
	return ventas

def convertirEuros(ventas):
	for v in ventas:
		v.total = round((v.total / Decimal(8.87)),2)
	return ventas	


#Vista para listar el detalle de las ventas
def detalle_ventas(request,pk):
	v = Ventas.objects.filter(pk=pk)
	v = v.iterator().next()
	detalles = DetalleVentas.objects.filter(venta=pk)
	tipo = Configuraciones.objects.get(pk=1)
	tipo = tipo.tipo_cambio
	nom = Configuraciones.objects.get(pk=1)
	if(tipo == "D"):
		detalles = detalleDolares(detalles)
		contexto = {'detalles':detalles,'total': round((v.total / Decimal(7.72)),2),'nombreE':nom.nombre}
		return render(request,'ventas/ventas_detalleD.html',contexto)
	if tipo == "E":
		detalles = detalleEuros(detalles)
		contexto = {'detalles':detalles,'total':round((v.total / Decimal(8.87)),2),'nombreE':nom.nombre}
		return render(request,'ventas/ventas_detalleE.html',contexto)
	contexto = {'detalles':detalles,'total':v.total,'nombreE':nom.nombre}
	return render(request,'ventas/ventas_detalle.html',contexto)

def detalleDolares(detalle):
	for d in detalle:
		d.servicio.precio = round((d.servicio.precio / Decimal(7.72)),2)
	return detalle

def detalleEuros(detalle):
	for d in detalle:
		d.servicio.precio = round((d.servicio.precio / Decimal(8.87)),2)
	return detalle

def venta_programada(request,pk):
	detalleC = DetalleCarnet.objects.filter(pk=pk)
	detalleC = detalleC.iterator().next()
	carnet = Carnet.objects.filter(pk = detalleC.carnet.id)
	carnet = carnet.iterator().next()
	v = Ventas(
		#fecha = timezone.now(),
		fecha=datetime.today(),
		cantidad = 1,
		total = detalleC.servicio.precio,
		carnet = carnet
	)
	v.save()
	print v
	detalle = DetalleVentas(
		venta = v,
		servicio = detalleC.servicio,
	)
	detalle.save()
	detalleC.estado = True
	detalleC.save()
	return redirect('ventas:ventas_listar')

Veterinaria/templates/ventas/ventas_form.html
{% extends 'base/base.html'%}
{% block nombreEmpresa %}
    <a class="navbar-brand" href="{% url 'general:resumen_datos' %}">
      <i class="fa fa-fw fa-home"></i>
      <span class="navbar-brand">{{ nombreE }}</span>
    </a>
{% endblock %}
{% block content %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
<script type="text/javascript">
    var serviciosS = [];
    serviciosS.push(0);//se crea el por defecto
    $(function () {
        $('.add-row').click(function() {
            addForm(this, 'form');
            var fil = $("#id_forms_table").find(".dynamic-form").last();
            $(fil).find("#sub").text("0.00");
            serviciosS.push(0);
        });
        $('.delete-row').click(function() {
            var padre = $(this).parent();
            padre = $(padre).parent();
            var index = padre.index();
            console.log("Fila " , index);
            if(index>0){
                var eliminado = serviciosS.splice(index, 1);
                console.log("eliminado " , eliminado);
                deleteForm(this, 'form');
            }
            else{
                alert("No puede eliminar el ultimo servicio");
            }
            calcularTotal()
        });
        $('#serv').change(function() {
            //var dfdfdf = $(this).index
            //console.log("index " , dfdfdf);
            var optionSelected = $(this).find("option:selected");//se obtiene el seleccionado
            var padre = $(this).parent();
            console.log("dfadfd " , padre.index())
            var index = optionSelected.index();
            if(index != 0){
                var Id  = optionSelected.val();//se obtiene el id seleccionado
                //getPrecio(Id,padre);
                if(verificarServicio(Id,padre.index())==false){
                    alert("Servicio Repetido");
                    optionSelected.selectedIndex = 0;
                }
                else{
                    getExistencia(Id,padre);
                }
            }
        });
        function verificarServicio(Id,Index){
            var bandera = true;
            if(serviciosS.length == 0){
                serviciosS.push(Id);
                return true;
            }
            else{
                serviciosS.forEach(function (elemento, indice, array) {
                    if(elemento==Id){
                        bandera = false;
                    }
                });
                if(bandera){
                    serviciosS[Index] = Id;
                }
            }
            return bandera;
        }
        function getPrecio(Id,padre){
            //falta el editar cuando se elimina
            //cuando se agrega que inicie con 0 o en blanco
            var request = $.ajax({
                type: "GET",
                url: "{% url 'servicios:get_precio' %}",
                data: {
                    "id": Id,
                },
                success: function (data) {
                    var object = JSON.parse(data);
                    //verificar si no altera otras filas
                    $(padre).find('#sub').text(object.precio);
                    calcularTotal();
                }
            });
            return 0;
        }
        function getExistencia(Id,padre){
            var request = $.ajax({
                type: "GET",
                url: "{% url 'servicios:get_existencia' %}",
                data: {
                    "id": Id,
                    'datos[]': JSON.stringify(serviciosS),
                },
                success: function (data) {
                    var object = JSON.parse(data);
                    var respuesta = object.resp
                    var nombre = object.nombre
                    if(respuesta == false){
                        alert("Servicio " + nombre + " sin Existencias"); 
                    }else{
                        getPrecio(Id,padre);
                    }               
                }
            });
        }
        function calcularTotal(){
            var suma = 0.00;
            $(".dynamic-form").find('#sub').each(function(){
                suma+=parseFloat($(this).html()) || 0;
            });
            $("#campoT").text("Q " + suma);
        }

    });
</script>
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="{% url 'ventas:ventas_listar' %}">Ventas</a>
    </li>
    <li class="breadcrumb-item active">Nueva Venta</li>
</ol>
<div class="card mb-3">
	<div class="card-header">
	<i class="fa fa-plus-square"></i>  Datos de la Venta</div>
	<div class="card-body">
		<form method="post" id="myForm">
			<!--token de seguridad, IMPORTANTE INCLUIRLO EN TODOS LOS FORMULARIOS-->
			{% csrf_token %} 
			{{form.as_p}}
			<div class="card-header">
			<i class="fa fa-table"></i> Agregar Servicios a la Venta</div>
			<div class="table-responsive">
				<table id="id_forms_table" class="table table-bordered" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Servicio</th>
						<th>Precio Quetzales</th>
						<th>Accion</th>
					</tr>
				</thead>
				<tbody>
					{% for formd in form2 %}
					<tr id="{{ form.prefix }}-row" class="dynamic-form">
						<td id="serv">{{formd.servicio}}</td>
						<td id="sub" class="text-center">0.00</td>
						<td class="text-center">
							<a id="remove-{{ form.prefix }}-row" href="javascript:void(0)" class="delete-row"><i class="fa fa-minus-circle"></i>  Eliminar</a>
						</td>
					</tr>
					<tr>
		    	    </tr>
					{% endfor %}
				</tbody>
				<td colspan="4"><a href="javascript:void(0)" class="add-row"><i class="fa fa-plus-circle"></i>  Agregar Servicio</a></td>
				</table>
				<div class="card-header">
					<div class="row">
						<div class="col-sm-8">
							<button class="btn btn-primary" type="submit">
							<i class="fa fa-cart-plus"></i> Guardar</button>
						</div>
						<div class="col-sm-2">
							<h6 align="right" class="card-text">Total</h6>
						</div>
						<div class="col-sm-2">
							<h6 align="center" class="card-text" id="campoT">Q 0.00</h6>
						</div>
					</div>
				</div>
			</div>
			{{ form2.management_form }}
		</form>
	</div>
</div>
{% endblock %}

Veterinaria/templates/ventas/ventas_formD.html
{% extends 'base/base.html'%}
{% block nombreEmpresa %}
    <a class="navbar-brand" href="{% url 'general:resumen_datos' %}">
      <i class="fa fa-fw fa-home"></i>
      <span class="navbar-brand">{{ nombreE }}</span>
    </a>
{% endblock %}
{% block content %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
<script type="text/javascript">
    var serviciosS = [];
    serviciosS.push(0);//se crea el por defecto
    $(function () {
        $('.add-row').click(function() {
            addForm(this, 'form');
            var fil = $("#id_forms_table").find(".dynamic-form").last();
            $(fil).find("#sub").text("0.00");
            serviciosS.push(0);
        });
        $('.delete-row').click(function() {
            var padre = $(this).parent();
            padre = $(padre).parent();
            var index = padre.index();
            console.log("Fila " , index);
            if(index>0){
                var eliminado = serviciosS.splice(index, 1);
                console.log("eliminado " , eliminado);
                deleteForm(this, 'form');
            }
            else{
                alert("No puede eliminar el ultimo servicio");
            }
            calcularTotal()
        });
        $('#serv').change(function() {
            //var dfdfdf = $(this).index
            //console.log("index " , dfdfdf);
            var optionSelected = $(this).find("option:selected");//se obtiene el seleccionado
            var padre = $(this).parent();
            console.log("dfadfd " , padre.index())
            var index = optionSelected.index();
            if(index != 0){
                var Id  = optionSelected.val();//se obtiene el id seleccionado
                //getPrecio(Id,padre);
                if(verificarServicio(Id,padre.index())==false){
                    alert("Servicio Repetido");
                    optionSelected.selectedIndex = 0;
                }
                else{
                    getExistencia(Id,padre);
                }
            }
        });
        function verificarServicio(Id,Index){
            var bandera = true;
            if(serviciosS.length == 0){
                serviciosS.push(Id);
                return true;
            }
            else{
                serviciosS.forEach(function (elemento, indice, array) {
                    if(elemento==Id){
                        bandera = false;
                    }
                });
                if(bandera){
                    serviciosS[Index] = Id;
                }
            }
            return bandera;
        }
        function getPrecio(Id,padre){
            //falta el editar cuando se elimina
            //cuando se agrega que inicie con 0 o en blanco
            var request = $.ajax({
                type: "GET",
                url: "{% url 'servicios:get_precio' %}",
                data: {
                    "id": Id,
                },
                success: function (data) {
                    var object = JSON.parse(data);
                    //verificar si no altera otras filas
                    $(padre).find('#sub').text(object.precio);
                    calcularTotal();
                }
            });
            return 0;
        }
        function getExistencia(Id,padre){
            var request = $.ajax({
                type: "GET",
                url: "{% url 'servicios:get_existencia' %}",
                data: {
                    "id": Id,
                    'datos[]': JSON.stringify(serviciosS),
                },
                success: function (data) {
                    var object = JSON.parse(data);
                    var respuesta = object.resp
                    var nombre = object.nombre
                    if(respuesta == false){
                        alert("Servicio " + nombre + " sin Existencias"); 
                    }else{
                        getPrecio(Id,padre);
                    }               
                }
            });
        }
        function calcularTotal(){
            var suma = 0.00;
            $(".dynamic-form").find('#sub').each(function(){
                suma+=parseFloat($(this).html()) || 0;
            });
            $("#campoT").text("$ " + suma);
        }

    });
</script>
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="{% url 'ventas:ventas_listar' %}">Ventas</a>
    </li>
    <li class="breadcrumb-item active">Nueva Venta</li>
</ol>
<div class="card mb-3">
	<div class="card-header">
	<i class="fa fa-plus-square"></i>  Datos de la Venta</div>
	<div class="card-body">
		<form method="post" id="myForm">
			<!--token de seguridad, IMPORTANTE INCLUIRLO EN TODOS LOS FORMULARIOS-->
			{% csrf_token %} 
			{{form.as_p}}
			<div class="card-header">
			<i class="fa fa-table"></i> Agregar Servicios a la Venta</div>
			<div class="table-responsive">
				<table id="id_forms_table" class="table table-bordered" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Servicio</th>
						<th>Precio Dolares</th>
						<th>Accion</th>
					</tr>
				</thead>
				<tbody>
					{% for formd in form2 %}
					<tr id="{{ form.prefix }}-row" class="dynamic-form">
						<td id="serv">{{formd.servicio}}</td>
						<td id="sub" class="text-center">0.00</td>
						<td class="text-center">
							<a id="remove-{{ form.prefix }}-row" href="javascript:void(0)" class="delete-row"><i class="fa fa-minus-circle"></i>  Eliminar</a>
						</td>
					</tr>
					<tr>
		    	    </tr>
					{% endfor %}
				</tbody>
				<td colspan="4"><a href="javascript:void(0)" class="add-row"><i class="fa fa-plus-circle"></i>  Agregar Servicio</a></td>
				</table>
				<div class="card-header">
					<div class="row">
						<div class="col-sm-8">
							<button class="btn btn-primary" type="submit">
							<i class="fa fa-cart-plus"></i> Guardar</button>
						</div>
						<div class="col-sm-2">
							<h6 align="right" class="card-text">Total</h6>
						</div>
						<div class="col-sm-2">
							<h6 align="center" class="card-text" id="campoT">$ 0.00</h6>
						</div>
					</div>
				</div>
			</div>
			{{ form2.management_form }}
		</form>
	</div>
</div>
{% endblock %}

Veterinaria/templates/ventas/ventas_list.html
{% extends 'base/base.html'%}
{% block nombreEmpresa %}
    <a class="navbar-brand" href="{% url 'general:resumen_datos' %}">
      <i class="fa fa-fw fa-home"></i>
      <span class="navbar-brand">{{ nombreE }}</span>
    </a>
{% endblock %}
{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="#">Ventas</a>
    </li>
        <li class="breadcrumb-item active">Listado</li>
</ol>
<div class="card mb-3">
	<div class="card-header">
		<i class="fa fa-table"></i> Ventas Realizadas</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Fecha</th>
						<th>Cliente</th>
						<th>Codigo Carnet</th>
						<th>Mascota</th>
						<th>Total Servicios</th>
						<th>Monto Total</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
					{% if ventas %}
					{% for venta in ventas %}
					<tr>
						<td>{{ venta.fecha }}</td>
						<td>{{ venta.carnet.mascota.cliente }}</td>
						<td>{{ venta.carnet.codigoC }}</td>
						<td>{{ venta.carnet.mascota.nombre }}</td>
						<td>{{ venta.cantidad }}</td>
						<td>Q {{ venta.total }}</td>
						<td class="text-center">
							<a class="btn btn-primary" href="{% url 'ventas:ventas_detalle' venta.id %}"><i class="fa fa-info-circle"></i>  Ver Detalle</a>
						</td>
					</tr>
					{% endfor %}
					{% else %}
					<h3>No hay Servicios creados :( </h3>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

Veterinaria/templates/ventas/ventas_listD.html
{% extends 'base/base.html'%}
{% block nombreEmpresa %}
    <a class="navbar-brand" href="{% url 'general:resumen_datos' %}">
      <i class="fa fa-fw fa-home"></i>
      <span class="navbar-brand">{{ nombreE }}</span>
    </a>
{% endblock %}
{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="#">Ventas</a>
    </li>
        <li class="breadcrumb-item active">Listado</li>
</ol>
<div class="card mb-3">
	<div class="card-header">
		<i class="fa fa-table"></i> Ventas Realizadas</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Fecha</th>
						<th>Cliente</th>
						<th>Codigo Carnet</th>
						<th>Mascota</th>
						<th>Total Servicios</th>
						<th>Monto Total</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
					{% if ventas %}
					{% for venta in ventas %}
					<tr>
						<td>{{ venta.fecha }}</td>
						<td>{{ venta.carnet.mascota.cliente }}</td>
						<td>{{ venta.carnet.codigoC }}</td>
						<td>{{ venta.carnet.mascota.nombre }}</td>
						<td>{{ venta.cantidad }}</td>
						<td>$ {{ venta.total }}</td>
						<td class="text-center">
							<a class="btn btn-primary" href="{% url 'ventas:ventas_detalle' venta.id %}"><i class="fa fa-info-circle"></i>  Ver Detalle</a>
						</td>
					</tr>
					{% endfor %}
					{% else %}
					<h3>No hay Servicios creados :( </h3>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

Veterinaria/templates/ventas/ventas_listE.html
{% extends 'base/base.html'%}
{% block nombreEmpresa %}
    <a class="navbar-brand" href="{% url 'general:resumen_datos' %}">
      <i class="fa fa-fw fa-home"></i>
      <span class="navbar-brand">{{ nombreE }}</span>
    </a>
{% endblock %}
{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="#">Ventas</a>
    </li>
        <li class="breadcrumb-item active">Listado</li>
</ol>
<div class="card mb-3">
	<div class="card-header">
		<i class="fa fa-table"></i> Ventas Realizadas</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Fecha</th>
						<th>Cliente</th>
						<th>Codigo Carnet</th>
						<th>Mascota</th>
						<th>Total Servicios</th>
						<th>Monto Total</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
					{% if ventas %}
					{% for venta in ventas %}
					<tr>
						<td>{{ venta.fecha }}</td>
						<td>{{ venta.carnet.mascota.cliente }}</td>
						<td>{{ venta.carnet.codigoC }}</td>
						<td>{{ venta.carnet.mascota.nombre }}</td>
						<td>{{ venta.cantidad }}</td>
						<td>£ {{ venta.total }}</td>
						<td class="text-center">
							<a class="btn btn-primary" href="{% url 'ventas:ventas_detalle' venta.id %}"><i class="fa fa-info-circle"></i>  Ver Detalle</a>
						</td>
					</tr>
					{% endfor %}
					{% else %}
					<h3>No hay Servicios creados :( </h3>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}