Veterinaria/Veterinaria/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

from myapps.general.views import Configuraciones

#URL's globales
#Aca van a ir las url de cada aplicacion
#Iran organizadas en orden.


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^carnet/', include('myapps.carnet.urls',namespace='carnet')),
    url(r'^clientes/', include('myapps.clientes.urls',namespace='clientes')),
    url(r'^inventario/', include('myapps.inventario.urls',namespace='inventario')),
    url(r'^planilla/', include('myapps.planilla.urls',namespace='planilla')),
    url(r'^servicios/', include('myapps.servicios.urls',namespace='servicios')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
    url(r'^usuario/', include('myapps.usuario.urls',namespace='usuario')),
     url(r'^logout/', logout_then_login, name='logout'),
     url(r'^$', login, {'template_name':'login.html'}, name='login'),
     url(r'^reset/password_reset', password_reset,
        {'template_name':'registration/forgot-password.html',
        'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),


    url(r'^ventas/', include('myapps.ventas.urls',namespace='ventas')),
    url(r'^index/', include('myapps.general.urls',namespace='general')),

]

Veterinaria/myapps/carnet/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from myapps.carnet.views import index, CarnetCreate, CarnetList, servicio_futuro, listar_proximasCitas,\
carnet_detalle, carnet_list

#URL's de la aplicacion
#Se listan todas las urls de la aplicacion
urlpatterns = [
    url(r'^$', index),
    url(r'^nuevo', login_required(CarnetCreate.as_view()), name='carnet_crear'),
    url(r'^listar', login_required(CarnetList.as_view()), name='carnet_listar'),
    url(r'^carnets_mascotas/(?P<pk>\d+)$', login_required(carnet_list), name='mascota_carnets'),
    url(r'^detalle_todo/(?P<pk>\d+)$', login_required(carnet_detalle), name='carnet_detalle_todo'),
    url(r'^programar_cita', login_required(servicio_futuro), name='carnet_proximaCita'),
    url(r'^citas_programadas/(?P<pk>\d+)$', login_required(listar_proximasCitas), name='carnet_citasProgramadas'),
]

Veterinaria/myapps/clientes/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from myapps.clientes.views import index
from myapps.clientes.views import index, cliente_create ,ClientesList, ClienteCreate
from myapps.clientes.views import pet_create,PetList,PetCreate, pet_list, PetEdit, ClienteEdit,matar_mascota
#URL's de la aplicacion
#Se listan todas las urls de la aplicacion
urlpatterns = [
    url(r'^$', index),
    url(r'^listar', login_required(ClientesList.as_view()), name='clientes_listar'),
    url(r'^nuevo', login_required(ClienteCreate.as_view()), name='cliente_crear'),
    url(r'^editar/(?P<pk>\d+)$',login_required(ClienteEdit.as_view()), name='cliente_editar'),
    url(r'^nuevamascota', login_required(pet_create), name='mascota_crear'),
    url(r'^mascota_editar/(?P<pk>\d+)$',login_required(PetEdit.as_view()), name='mascota_editar'),
    url(r'^mascotas_listar/(?P<pk>\d+)$', login_required(pet_list),name='mascota_listar'),
    url(r'^anular_mascota/(?P<pk>\d+)$', login_required(matar_mascota),name='matar_mascota'),
]

Veterinaria/myapps/general/urls.py
from django.conf.urls import url

from myapps.general.views import calcular_total
from django.contrib.auth.decorators import login_required

from myapps.general.views import ConfiUpdate
#URL's de la aplicacion
#Se listan todas las urls de la aplicacion
urlpatterns = [
    url(r'^$',  login_required(calcular_total), name='resumen_datos'),
    url(r'^parametrizacion/(?P<pk>\d+)$',  login_required(ConfiUpdate.as_view()), name='configuracion'),

]

Veterinaria/myapps/ventas/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from myapps.ventas.views import index, venta_create, ventas_list, detalle_ventas,venta_programada


urlpatterns = [
	url(r'^$', index),
	url(r'^nuevo', login_required(venta_create), name='ventas_crear'),
	url(r'^listar', login_required(ventas_list), name='ventas_listar'),
	url(r'^detalle/(?P<pk>\d+)$', login_required(detalle_ventas), name='ventas_detalle'),
	url(r'^programada/(?P<pk>\d+)$', login_required(venta_programada), name='ventas_programadas'),
]

Veterinaria/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	{% block Title %}
	<title>VetCare</title>
	{% endblock %}
	<script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/dynamic-formset.js' %}"></script>
	<!-- Bootstrap core CSS-->
  	<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  	<!-- Custom fonts for this template-->
  	<link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  	<!-- Page level plugin CSS-->
  	<link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
  	<!-- Custom styles for this template-->
  	<link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

	{% block extrahead %}
	{% endblock %}
</head>
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
	{% block navbar %}

  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    {% block nombreEmpresa %}
    <a class="navbar-brand" href="{% url 'general:resumen_datos' %}">
      <i class="fa fa-fw fa-home"></i>
      <span class="navbar-brand">VetCare</span>
    </a>
    {% endblock %}
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Inventario">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMenu1" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-shopping-cart"></i>
            <span class="nav-link-text">Inventario</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMenu1">
            <li>
              <a href="{% url 'inventario:inventario_crear' %}">Crear Insumo</a>
            </li>
            <li>
              <a href="{% url 'inventario:inventario_listar' %}">Mostrar Inventario</a>
            </li>
          </ul>
        </li>
       <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Clientes">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMenu2" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-male"></i>
            <span class="nav-link-text">Clientes y Mascotas</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMenu2">
            <li>
              <a href="{% url 'clientes:cliente_crear' %}">Crear Cliente</a>
            </li>
            <li>
              <a href="{% url 'clientes:mascota_crear' %}">Ingresar Mascota</a>
            </li>
            <li>
              <a href="{% url 'clientes:clientes_listar' %}">Mostrar Clientes</a>
            </li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Mascotas">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMenu3" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-address-card"></i>
            <span class="nav-link-text">Carnets</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMenu3">
            <li>
              <a href="{% url 'carnet:carnet_crear' %}">Crear Carnet</a>
            </li>
            <li>
              <a href="{% url 'carnet:carnet_listar' %}">Mostrar Carnets</a>
            </li>
            <li>
              <a href="{% url 'carnet:carnet_proximaCita' %}">Programar un Servicio</a>
            </li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Servicios">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMenu4" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-stethoscope"></i>
            <span class="nav-link-text">Servicios</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMenu4">
            <li>
              <a href="{% url 'servicios:servicios_crear' %}">Crear Servicio</a>
            </li>
            <li>
              <a href="{% url 'servicios:servicios_listar' %}">Mostrar Servicios</a>
            </li>
            <li>
              <a href="{% url 'ventas:ventas_crear' %}">Realizar Servicio</a>
            </li>
            <li>
              <a href="{% url 'ventas:ventas_listar' %}">Ver Ventas</a>
            </li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Planilla">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMenu5" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-group"></i>
            <span class="nav-link-text">Planilla</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMenu5">
            <li>
              <a href="{% url 'planilla:empleados_crear' %}">Crear Empleado</a>
            </li>
            <li>
              <a href="{% url 'planilla:planilla_crear' %}">Crear Planilla</a>
            </li>
            <li>
              <a href="{% url 'planilla:planilla_listar' %}">Mostrar Planillas</a>
            </li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Configuraciones">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMenu6" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-cog"></i>
            <span class="nav-link-text">Configuraciones</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMenu6">
            <li>
              <a href="{% url 'general:configuracion' 1 %}">Parametrizaciones</a>
            </li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">

            <a href="{% url 'logout' %}" class="nav-link" data-target="#exampleModal">
               <i class="fa fa-fw fa-sign-out"></i>Cerrar Sesión</a>


      </ul>
    </div>

  </nav>
  <!-- Bootstrap core JavaScript-->
    <script src="../../static/vendor/jquery/jquery.min.js"></script>
    <script src="../../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="../../static/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="../../static/js/sb-admin.min.js"></script>
    <!-- Custom scripts for this page-->
    <!-- Toggle between fixed and static navbar-->
  <script>
    $('#toggleNavPosition').click(function() {
      $('body').toggleClass('fixed-nav');
      $('nav').toggleClass('fixed-top static-top');
    });
    </script>
{% endblock %}
	<div class="content-wrapper">
		<div class="container-fluid">
			<!-- Bloque donde van los listados o formularios -->
			{% block content %}
			<h1>Bloque de contenido</h1>
			{% endblock %}
		</div>
	</div>
	{% block footer %}
	{% include 'base/footer.html' %}
	{% endblock%}
	<!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
</body>
</html>

Veterinaria/templates/base/baseUsuario.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

	<title>Veterinaria</title>
	<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<!-- Custom fonts for this template-->
	<link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
	<!-- Page level plugin CSS-->

	<!-- Custom styles for this template-->
	<link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
	{% block extrahead %}
	{% endblock %}
</head>
<body class="bg-dark">
	<div class="container">

	{% block content %}
	<h1>Hola :3 </h1>
	{% endblock %}

	{% block footer %}
	<footer>
		<div>
			<p>&copy; 2018 Grupito</p>
		</div>
	</footer>
	{% endblock%}

	</div>



</body>
</html>

Veterinaria/templates/base/footer.html
{% block footer %}
<footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Vetcare 2018 - Derechos Reservados</small>
        </div>
      </div>
    </footer>
{% endblock %}

Veterinaria/templates/base/header.html
<header>Veterinaria</header>

Veterinaria/templates/base/index.html
{% extends 'base/base.html'%}
{% block nombreEmpresa %}
    <a class="navbar-brand" href="{% url 'general:resumen_datos' %}">
      <i class="fa fa-fw fa-home"></i>
      <span class="navbar-brand">{{ nombreE }}</span>
    </a>
    {% endblock %}
{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="#">Resumen</a>
	</li>
	<li class="breadcrumb-item active">{{ nombreE }}</li>
</ol>
<!-- Icon Cards-->
<div class="row">
	<!-- Dato total Inventario-->
	<div class="col-xl-3 col-sm-6 mb-3">
		<div class="card text-white bg-primary o-hidden h-100">
			<div class="card-body">
				<div class="card-body-icon">
					<i class="fa fa-fw fa-barcode"></i>
				</div>
				<div class="mr-5">{{ insumos }} Insumos!</div>
			</div>
		</div>
	</div>
	<!-- Dato total Clientes-->
	<div class="col-xl-3 col-sm-6 mb-3">
		<div class="card text-white bg-warning o-hidden h-100">
			<div class="card-body">
				<div class="card-body-icon">
					<i class="fa fa-fw fa-users"></i>
				</div>
				<div class="mr-5">{{ clientes }} Clientes!</div>
			</div>
		</div>
	</div>
	<!-- Dato total Clientes-->
	<div class="col-xl-3 col-sm-6 mb-3">
		<div class="card text-white bg-success o-hidden h-100">
			<div class="card-body">
				<div class="card-body-icon">
					<i class="fa fa-fw fa-paw"></i>
				</div>
				<div class="mr-5">{{ mascotas }} Mascotas!</div>
			</div>
		</div>
	</div>
	<!-- Dato total Clientes-->
	<div class="col-xl-3 col-sm-6 mb-3">
		<div class="card text-white bg-danger o-hidden h-100">
			<div class="card-body">
				<div class="card-body-icon">
					<i class="fa fa-fw fa-medkit"></i>
				</div>
				<div class="mr-5">{{ servicios }} Servicios!</div>
			</div>
		</div>
	</div>
	<div class="col-xl-3 col-sm-6 mb-3">
		<div class="card text-white bg-primary o-hidden h-100">
			<div class="card-body">
				<div class="card-body-icon">
					<i class="fa fa-fw fa-user-circle"></i>
				</div>
				<div class="mr-5">{{ empleados }} Empleados!</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

Veterinaria/templates/base/navbar.html
{% block navbar %}

  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    {% block nombreEmpresa %}
    <a class="navbar-brand" href="{% url 'general:resumen_datos' %}">
      <i class="fa fa-fw fa-home"></i>
      <span class="navbar-brand">VetCare</span>
    </a>
    {% endblock %}
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Inventario">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMenu1" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-shopping-cart"></i>
            <span class="nav-link-text">Inventario</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMenu1">
            <li>
              <a href="{% url 'inventario:inventario_crear' %}">Crear Insumo</a>
            </li>
            <li>
              <a href="{% url 'inventario:inventario_listar' %}">Mostrar Inventario</a>
            </li>
          </ul>
        </li>
       <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Clientes">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMenu2" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-male"></i>
            <span class="nav-link-text">Clientes y Mascotas</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMenu2">
            <li>
              <a href="{% url 'clientes:cliente_crear' %}">Crear Cliente</a>
            </li>
            <li>
              <a href="{% url 'clientes:mascota_crear' %}">Ingresar Mascota</a>
            </li>
            <li>
              <a href="{% url 'clientes:clientes_listar' %}">Mostrar Clientes</a>
            </li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Mascotas">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMenu3" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-address-card"></i>
            <span class="nav-link-text">Carnets</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMenu3">
            <li>
              <a href="{% url 'carnet:carnet_crear' %}">Crear Carnet</a>
            </li>
            <li>
              <a href="{% url 'carnet:carnet_listar' %}">Mostrar Carnets</a>
            </li>
            <li>
              <a href="{% url 'carnet:carnet_proximaCita' %}">Programar un Servicio</a>
            </li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Servicios">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMenu4" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-stethoscope"></i>
            <span class="nav-link-text">Servicios</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMenu4">
            <li>
              <a href="{% url 'servicios:servicios_crear' %}">Crear Servicio</a>
            </li>
            <li>
              <a href="{% url 'servicios:servicios_listar' %}">Mostrar Servicios</a>
            </li>
            <li>
              <a href="{% url 'ventas:ventas_crear' %}">Realizar Servicio</a>
            </li>
            <li>
              <a href="{% url 'ventas:ventas_listar' %}">Ver Ventas</a>
            </li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Planilla">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMenu5" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-group"></i>
            <span class="nav-link-text">Planilla</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMenu5">
            <li>
              <a href="{% url 'planilla:empleados_crear' %}">Crear Empleado</a>
            </li>
            <li>
              <a href="{% url 'planilla:planilla_crear' %}">Crear Planilla</a>
            </li>
            <li>
              <a href="{% url 'planilla:planilla_listar' %}">Mostrar Planillas</a>
            </li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Configuraciones">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMenu6" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-cog"></i>
            <span class="nav-link-text">Configuraciones</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMenu6">
            <li>
              <a href="{% url 'general:configuracion' 1 %}">Parametrizaciones</a>
            </li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">

            <a href="{% url 'logout' %}" class="nav-link" data-target="#exampleModal">
               <i class="fa fa-fw fa-sign-out"></i>Cerrar Sesión</a>


      </ul>
    </div>

  </nav>
  <!-- Bootstrap core JavaScript-->
    <script src="../../static/vendor/jquery/jquery.min.js"></script>
    <script src="../../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="../../static/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="../../static/js/sb-admin.min.js"></script>
    <!-- Custom scripts for this page-->
    <!-- Toggle between fixed and static navbar-->
  <script>
    $('#toggleNavPosition').click(function() {
      $('body').toggleClass('fixed-nav');
      $('nav').toggleClass('fixed-top static-top');
    });
    </script>
{% endblock %}

Veterinaria/templates/base/parametrizacion.html
{% extends 'base/base.html'%}

{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="{% url 'clientes:clientes_listar' %}">General</a>
    </li>
        <li class="breadcrumb-item active">Parametrización</li>
</ol>
<div class="card mb-3">
	<div class="card-header">
		<i class="fa fa-plus-square"></i>  Configuraciones</div>
		<div class="card-body">
			<!-- Adentro de este div va lo que se quiera mostar-->
		<form method="post">
			<!--token de seguridad, IMPORTANTE INCLUIRLO EN TODOS LOS FORMULARIOS-->
			{% csrf_token %} 
			{{form.as_p}}
			<button class="btn btn-primary" type="submit">
				<i class="fa fa-check-square"></i> Guardar</button>
		</form>
		</div>
	</div>
</div>
{% endblock %}

Veterinaria/templates/base/registrar.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label>Nombre</label>
				<input class="form-control" type="text" name="first_name">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Apellidos</label>
				<input class="form-control" type="text" name="last_name">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Nombre de usuario</label>
				<input class="form-control" type="text" name="username">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Correo</label>
				<input class="form-control" type="text" name="email">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Contraseña</label>
				<input class="form-control" type="password" name="password1">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Confirmar contraseña</label>
				<input class="form-control" type="password" name="password2">
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Otro</label>
				<input class="form-control" type="text" name="otro"	>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
			</div>
		</div>
	</div>

</form>
{% endblock %}