Veterinaria/Veterinaria/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

from myapps.general.views import Configuraciones

#URL's globales
#Aca van a ir las url de cada aplicacion
#Iran organizadas en orden.


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^carnet/', include('myapps.carnet.urls',namespace='carnet')),
    url(r'^clientes/', include('myapps.clientes.urls',namespace='clientes')),
    url(r'^inventario/', include('myapps.inventario.urls',namespace='inventario')),
    url(r'^planilla/', include('myapps.planilla.urls',namespace='planilla')),
    url(r'^servicios/', include('myapps.servicios.urls',namespace='servicios')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
    url(r'^usuario/', include('myapps.usuario.urls',namespace='usuario')),
     url(r'^logout/', logout_then_login, name='logout'),
     url(r'^$', login, {'template_name':'login.html'}, name='login'),
     url(r'^reset/password_reset', password_reset,
        {'template_name':'registration/forgot-password.html',
        'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),


    url(r'^ventas/', include('myapps.ventas.urls',namespace='ventas')),
    url(r'^index/', include('myapps.general.urls',namespace='general')),

]

Veterinaria/myapps/carnet/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from myapps.carnet.views import index, CarnetCreate, CarnetList, servicio_futuro, listar_proximasCitas,\
carnet_detalle, carnet_list

#URL's de la aplicacion
#Se listan todas las urls de la aplicacion
urlpatterns = [
    url(r'^$', index),
    url(r'^nuevo', login_required(CarnetCreate.as_view()), name='carnet_crear'),
    url(r'^listar', login_required(CarnetList.as_view()), name='carnet_listar'),
    url(r'^carnets_mascotas/(?P<pk>\d+)$', login_required(carnet_list), name='mascota_carnets'),
    url(r'^detalle_todo/(?P<pk>\d+)$', login_required(carnet_detalle), name='carnet_detalle_todo'),
    url(r'^programar_cita', login_required(servicio_futuro), name='carnet_proximaCita'),
    url(r'^citas_programadas/(?P<pk>\d+)$', login_required(listar_proximasCitas), name='carnet_citasProgramadas'),
]

Veterinaria/myapps/clientes/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from myapps.clientes.views import index
from myapps.clientes.views import index, cliente_create ,ClientesList, ClienteCreate
from myapps.clientes.views import pet_create,PetList,PetCreate, pet_list, PetEdit, ClienteEdit,matar_mascota
#URL's de la aplicacion
#Se listan todas las urls de la aplicacion
urlpatterns = [
    url(r'^$', index),
    url(r'^listar', login_required(ClientesList.as_view()), name='clientes_listar'),
    url(r'^nuevo', login_required(ClienteCreate.as_view()), name='cliente_crear'),
    url(r'^editar/(?P<pk>\d+)$',login_required(ClienteEdit.as_view()), name='cliente_editar'),
    url(r'^nuevamascota', login_required(pet_create), name='mascota_crear'),
    url(r'^mascota_editar/(?P<pk>\d+)$',login_required(PetEdit.as_view()), name='mascota_editar'),
    url(r'^mascotas_listar/(?P<pk>\d+)$', login_required(pet_list),name='mascota_listar'),
    url(r'^anular_mascota/(?P<pk>\d+)$', login_required(matar_mascota),name='matar_mascota'),
]

Veterinaria/myapps/servicios/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from myapps.servicios.views import index, servicios_list, servicios_create, ServiciosList, \
 									detalle_servicios,ServiciosUpdate,obtener_precio_ajax,\
 									existencia_servicio

#URL's de la aplicacion
#Se listan todas las urls de la aplicacion
urlpatterns = [
    url(r'^$', index),
    url(r'^listar', login_required(servicios_list), name='servicios_listar'),
    url(r'^nuevo', login_required(servicios_create), name='servicios_crear'),
    url(r'^detalle/(?P<pk>\d+)$', login_required(detalle_servicios), name='servicios_detalle'),
    url(r'^editar/(?P<pk>\d+)$', login_required(ServiciosUpdate.as_view()), name='servicios_editar'),
    url(r'^ajax/get_precio/$', obtener_precio_ajax, name='get_precio'),
    url(r'^ajax/get_existencia/$', existencia_servicio, name='get_existencia'),
]

Veterinaria/myapps/ventas/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from myapps.ventas.views import index, venta_create, ventas_list, detalle_ventas,venta_programada


urlpatterns = [
	url(r'^$', index),
	url(r'^nuevo', login_required(venta_create), name='ventas_crear'),
	url(r'^listar', login_required(ventas_list), name='ventas_listar'),
	url(r'^detalle/(?P<pk>\d+)$', login_required(detalle_ventas), name='ventas_detalle'),
	url(r'^programada/(?P<pk>\d+)$', login_required(venta_programada), name='ventas_programadas'),
]

Veterinaria/myapps/carnet/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from myapps.clientes.models import Mascota
from myapps.servicios.models import Servicios

# Create your models here.

#Modelo para la tabla Carnet
class Carnet(models.Model):
	ciclo = models.CharField(max_length = 45)
	mascota = models.ForeignKey(Mascota,null=True,blank=True)
	def __unicode__(self):
		return 'Carnet: {}-{} {}'.format(self.mascota.codigo, self.ciclo, self.mascota.nombre) #retornar el atributo
	def codigoC(self):
		return 'Carnet: {}-{}'.format(self.mascota.codigo,self.ciclo)

#Modelo para la tabla DetalleCarnet
class DetalleCarnet(models.Model):
	carnet = models.ForeignKey(Carnet,null=True,blank=True)
	servicio = models.ForeignKey(Servicios,null=True,blank=True)
	fecha = models.DateField()
	estado = models.BooleanField()

Veterinaria/myapps/carnet/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from myapps.carnet.models import Carnet, DetalleCarnet
from myapps.servicios.models import Servicios
from myapps.clientes.models import Mascota

#Formulario para ingresar nuevos carnet
class CarnetForm(forms.ModelForm):
	class Meta:
		model = Carnet
		#Campos del Modelo
		fields = [
			'ciclo',
			'mascota',
		]

		#Etiquetas que se mostraran el el formulario
		#Va el nombre del campo : Texto de la etiqueta
		labels = {
			'ciclo' : 'Ciclo',
			'mascota' : 'Mascota',
		}

		#Tipos de Campos para ingresar datos ej: TextBox, Combobox, checkbox, etc
		#Va el nombre del campo : Tipo de campo
		widgets = {
			'ciclo' : forms.TextInput(attrs={'class':'form-control'}),
			'mascota' : forms.Select(attrs={'class':'form-control'}),
			#'mascota' : forms.ModelChoiceField(queryset=Mascota.objects.all())
		}


#Formulario para programar un servicio futuro
class ServicioFuturoForm(forms.ModelForm):
	class Meta:
		DATE_INPUT_FORMATS = ['%Y-%m-%d']
		model = DetalleCarnet

		fields = [
			'carnet',
			'servicio',
			'fecha',
			'estado',
		]

		labels = {
			'carnet' : 'Carnet',
			'servicio' : 'Servicio',
			'fecha' : 'Fecha',
			'estado' : 'Cita Futura'
		}

		widgets = {
			'carnet' : forms.Select(attrs={'class':'form-control'}),
			'servicio' : forms.Select(attrs={'class':'form-control'}),
			#'fecha': forms.DateInput(attrs={'class':'form-control'}),
			'fecha' : forms.SelectDateWidget(),
			'estado' : forms.HiddenInput()
		}				

#Formulario para escoger los servicios
class ServicioMascotaForm(forms.ModelForm):
	class Meta:
		model = Servicios
		#revisar el attrs={'readonly':'readonly'}
		#Campos del Modelo
		fields = [
			'tipo_servicio',
			'precio',
		]

		labels = {
			'tipo_servicio' : 'Servicio',
			'precio' : 'Precio Q',
		}

		#Va el nombre del campo : Tipo de campo
		widgets = {
			'tipo_servicio' : forms.Select(attrs={'class':'form-control'}),
			'precio' : forms.TextInput(attrs={'class':'form-control','readonly':'readonly'}),
		}

#Formulario para escoger el carnet
class CarnetMascotaForm(forms.ModelForm):
	class Meta:
		model = Carnet

		#Campos del Modelo
		fields = [
			'mascota',
		]

		#Etiquetas que se mostraran el el formulario
		#Va el nombre del campo : Texto de la etiqueta
		labels = {
			'mascota' : 'Mascota',
		}

		#Tipos de Campos para ingresar datos ej: TextBox, Combobox, checkbox, etc
		#Va el nombre del campo : Tipo de campo
		widgets = {
			'mascota' : forms.Select(attrs={'class':'form-control'}),
		}

Veterinaria/myapps/carnet/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy

#Para vistas basadas en clases
from myapps.carnet.models import Carnet, DetalleCarnet
from myapps.clientes.models import Mascota
from myapps.carnet.forms import CarnetForm, ServicioFuturoForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
# Create your views here.

#Vista de prueba
def index(request):
	return HttpResponse('App de Carnet')


#vista para ingresar
class CarnetCreate(CreateView):
	model = Carnet
	form_class = CarnetForm
	template_name = 'carnet/carnet_form.html'
	success_url = reverse_lazy('carnet:carnet_listar')


#Vista para listar carnets
#Vista general
class CarnetList(ListView):
	model = Carnet
	template_name = 'carnet/carnet_list.html'

#Vista para listar carnets por un id de mascota
def carnet_list(request,pk):
	detalle = Carnet.objects.filter(mascota=pk).order_by('-ciclo')
	c = detalle.iterator().next()
	contexto = {'carnets':detalle,'mascota' : c.mascota}
	return render(request,'carnet/carnets_mascotas.html',contexto)

#Vista para listar todos los carnets segun una mascota
#Vista para listar todos los servicios en un carnet (Realizados y pendientes)
def carnet_detalle(request,pk):
	try:
		carnet = Carnet.objects.filter(pk=pk)
		detalle = DetalleCarnet.objects.filter(carnet=pk).order_by('-fecha')
	except DetalleCarnet.DoesNotExist:
		raise Http404("No existe detalle para este carnet")
	c = carnet.iterator().next()
	contexto = {'detalles':detalle,'carnet':c}
	return render(request,'carnet/detalle_carnet_list.html',contexto)
	
#Vista para listar los servicios que se han realizado 
def carnet_detalleRealizados(request,pk):
	try:
		detalle = DetalleCarnet.objects.get(carnet=pk,estado=1)#Servicios ya realizados
	except DetalleCarnet.DoesNotExist:
		raise Http404("No existe detalle para este carnet")
	contexto = {'detalles':detalle}
	return render(request,'mascota/mascota_list.html',contexto)

#Vistas para citas programadas (servicios futuros)
def servicio_futuro(request):
	if request.method == 'POST':
		form = ServicioFuturoForm(request.POST)
		#form.estado = False
		if form.is_valid():
			item = form.save(commit=False)
			item.estado = False
			item.save()
		return redirect('carnet:carnet_listar')
	else:
		form = ServicioFuturoForm()
	return render(request, 'carnet/servicio_futuro_form.html',{'form':form})

def listar_proximasCitas(request,pk):
	try:
		detalle = DetalleCarnet.objects.filter(carnet=pk,estado=0).order_by('fecha')
	except DetalleCarnet.DoesNotExist:
		raise Http404("Error al obtener las citas")
	contexto = {'detalles':detalle}
	return render(request,'carnet/citas_futuras.html',contexto)


#Vista para crear un servicio ya echo
def servicio_nuevo_echo(obVenta,obDetalle):
	citaCarnet = DetalleCarnet(
		carnet=obVenta.carnet,
		servicio=obDetalle.servicio,
		estado=True,
		fecha=obVenta.fecha,
	)
	citaCarnet.save()

Veterinaria/templates/carnet/carnet_form.html
{% extends 'base/base.html'%}
{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="{% url 'carnet:carnet_listar' %}">Carnet</a>
    </li>
        <li class="breadcrumb-item active">Crear</li>
</ol>
<div class="card mb-3">
	<div class="card-header">
		<i class="fa fa-plus-square"></i>  Datos del Carnet</div>
		<div class="card-body">
			<!-- Adentro de este div va lo que se quiera mostar-->
		<form method="post">
			<!--token de seguridad, IMPORTANTE INCLUIRLO EN TODOS LOS FORMULARIOS-->
			{% csrf_token %} 
			{{form.as_p}}
			<button class="btn btn-primary" type="submit">
				<i class="fa fa-check-square"></i> Guardar</button>
		</form>
		</div>
	</div>
</div>
{% endblock %}

Veterinaria/templates/carnet/carnet_list.html
{% extends 'base/base.html'%}

{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="#">Carnet</a>
    </li>
        <li class="breadcrumb-item active">Listado</li>
</ol>
<div class="card mb-3">
	<div class="card-header"><i class="fa fa-table"></i> Carnets Existentes</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Ciclo</th>
						<th>Codigo</th>
						<th>Mascota</th>
						<th>Dueño(a)</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
					{% if object_list %}
					{% for carnet in object_list %}
					<tr>
						<td>{{ carnet.ciclo }}</td>
						<td>{{ carnet.mascota.codigo }}</td>
						<td>{{ carnet.mascota.nombre }}</td>
						<td>{{ carnet.mascota.cliente }}</td>
						<td class="text-center">
							<a class="btn btn-primary" href="{% url 'carnet:carnet_detalle_todo' carnet.id %}"><i class="fa fa-info-circle"></i>   Ver Detalle</a>
							<a class="btn btn-primary" href="{% url 'carnet:carnet_citasProgramadas' carnet.id %}"><i class="fa fa-info-circle"></i>  Citas Futuras</a>
						</td>
					</tr>
					{% endfor %}
					{% else %}
					<h3>No hay Carnets creados :( </h3>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

Veterinaria/templates/carnet/carnets_mascotas.html
{% extends 'base/base.html'%}

{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="{% url 'clientes:clientes_listar' %}">Mascotas</a>
    </li>
        <li class="breadcrumb-item active">Listado de Carnets</li>
</ol>
<div class="card mb-3">
	<div class="card-header"><i class="fa fa-table"></i> Carnets Existentes para {{mascota.nombre}}</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Ciclo</th>
						<th>Codigo</th>
						<th>Dueño(a)</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
					{% if carnets %}
					{% for carnet in carnets %}
					<tr>
						<td>{{ carnet.ciclo }}</td>
						<td>{{ carnet.mascota.codigo }}</td>
						<td>{{ carnet.mascota.cliente }}</td>
						<td class="text-center">
							<a class="btn btn-primary" href="{% url 'carnet:carnet_detalle_todo' carnet.id %}"><i class="fa fa-info-circle"></i>   Ver Detalle</a>
							<a class="btn btn-primary" href="{% url 'carnet:carnet_citasProgramadas' carnet.id %}"><i class="fa fa-info-circle"></i>  Citas Futuras</a>
						</td>
					</tr>
					{% endfor %}
					{% else %}
					<h3>No hay Carnets creados :( </h3>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

Veterinaria/templates/carnet/citas_futuras.html
{% extends 'base/base.html'%}

{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="{% url 'carnet:carnet_listar' %}">Carnets</a>
    </li>
        <li class="breadcrumb-item active">Citas Programadas</li>
</ol>
<div class="card mb-3">
	<div class="card-header"><i class="fa fa-table"></i> Datos de las Citas</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Fecha</th>
						<th>Servicio</th>
						<th>Precio</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
					{% if detalles %}
					{% for detalle in detalles %}
					<tr>
						<td>{{ detalle.fecha }}</td>
						<td>{{ detalle.servicio }}</td>
						<td>Q {{ detalle.servicio.precio }}</td>
						<td class="text-center">
							<a class="btn btn-primary" href="{% url 'ventas:ventas_programadas' detalle.id %}"><i class="fa fa-cart-plus"></i>   Realizar Venta</a>
						</td>
					</tr>
					{% endfor %}
					{% else %}
					<h3>No hay Citas Programadas</h3>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

Veterinaria/templates/carnet/detalle_carnet_list.html
{% extends 'base/base.html'%}

{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="{% url 'carnet:carnet_listar' %}">Carnet</a>
    </li>
        <li class="breadcrumb-item active">Detalle</li>
</ol>
<div class="card mb-3">
	<div class="card-header"><i class="fa fa-table"></i> Servicios para {{carnet.codigoC}}</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Servicio</th>
						<th>Precio</th>
						<th>Fecha</th>
						<th>Estado</th>
					</tr>
				</thead>
				<tbody>
					{% if detalles %}
					{% for detalle in detalles %}
					<tr>
						<td>{{ detalle.servicio }}</td>
						<td>Q {{ detalle.servicio.precio }}</td>
						<td>{{ detalle.fecha }}</td>
						{% if detalle.estado %}
							<td class="text-center">Realizado</td>
						{% else %}
							<td class="text-center">Pendiente</td>
						{% endif %}
					</tr>
					{% endfor %}
					{% else %}
					<h3>No Servicios para este carnet </h3>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

Veterinaria/templates/carnet/servicio_futuro_form.html
{% extends 'base/base.html'%}

{% block content %}
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="{% url 'servicios:servicios_listar' %}">Servicios</a>
    </li>
        <li class="breadcrumb-item active">Programar Cita Futura</li>
</ol>
<div class="card mb-3">
	<div class="card-header">
		<i class="fa fa-plus-square"></i>  Crear Insumo</div>
		<div class="card-body">
			<!-- Adentro de este div va lo que se quiera mostar-->
		<form method="post">
			<!--token de seguridad, IMPORTANTE INCLUIRLO EN TODOS LOS FORMULARIOS-->
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-primary" type="submit">
				<i class="fa fa-check-square"></i> Guardar</button>
		</form>
		</div>
	</div>
</div>
{% endblock %}